import {Camera, LockKeyhole, Mail, MapPin, Phone, ShieldCheck, UserRound} from 'lucide-react';
import {useState} from 'react';
import {Button, Card, Field, PageHeader} from '../components/UI';
import {useApp} from '../lib/AppContext';
import {apiRequest, endpoints, unwrap} from '../lib/api';
import {isDemoSession} from '../lib/dataHelpers';

export function Profile({vendor = false}) {
  const {session} = useApp(); const user = session.user;
  return <div className="page"><PageHeader eyebrow={vendor ? 'Business account' : 'Customer account'} title="Profile" text="Your Merrage account details and quick account actions." /><div className="profile-layout"><Card className="profile-card"><img src={user.profileImage || '/assets/image/zz.jpg'} alt="" /><span className="role-pill">{user.role}</span><h2>{user.name}</h2><p><Phone />{user.phone}</p><p><Mail />{user.email}</p><p><MapPin />{user.address}</p></Card><div className="profile-actions"><Card><UserRound /><div><h3>Edit profile</h3><p>Update your photo, contact details, and address.</p></div><Button variant="soft" onClick={() => location.href = vendor ? '/vendor/profile/edit' : '/profile/edit'}>Open</Button></Card><Card><LockKeyhole /><div><h3>Change password</h3><p>Keep your account protected with a new password.</p></div><Button variant="soft" onClick={() => location.href = vendor ? '/vendor/change-password' : '/change-password'}>Open</Button></Card><Card><ShieldCheck /><div><h3>Privacy policy</h3><p>Understand how Merrage handles your account data.</p></div><Button variant="soft" onClick={() => location.href = vendor ? '/vendor/privacy' : '/privacy'}>Read</Button></Card></div></div></div>;
}

export function EditProfile({vendor = false}) {
  const {session, updateSessionUser, notify} = useApp(); const user = session.user; const [form, setForm] = useState({name: user.name || '', email: user.email || '', phone: user.phone || '', address: user.address || ''}); const [photo, setPhoto] = useState(null);
  const submit = async e => {e.preventDefault(); const body = new FormData(); Object.entries(form).forEach(([k, v]) => body.append(k, v)); if (photo) body.append('profileImage', photo); try {const response = isDemoSession(session) ? {} : await apiRequest(endpoints.editProfile, {method: 'PUT', token: session.token, body}); updateSessionUser({...form, ...(photo ? {profileImage: URL.createObjectURL(photo)} : {}), ...unwrap(response)}); notify('Profile updated successfully.');} catch (error) {notify(error.message, 'error');}};
  return <div className="page"><PageHeader eyebrow={vendor ? 'Vendor profile' : 'Personal profile'} title="Edit Profile" text="These details are sent to the profile update API and shown across your account." /><form className="edit-profile-layout" onSubmit={submit}><Card className="photo-upload-card"><div className="profile-photo"><img src={photo ? URL.createObjectURL(photo) : user.profileImage || '/assets/image/zz.jpg'} alt="" /><label><Camera /><input type="file" accept="image/*" onChange={e => setPhoto(e.target.files[0])} /></label></div><h3>{vendor ? 'Business photo' : 'Profile photo'}</h3><p>{photo ? `${photo.name} is ready to upload.` : 'Choose a clear photo to update your account.'}</p></Card><Card className="form-card"><span className="eyebrow">Editable details</span><h2>{vendor ? 'Business details' : 'Personal details'}</h2><div className="form-grid"><Field label={vendor ? 'Business or contact name' : 'Full name'} required value={form.name} onChange={e => setForm({...form, name: e.target.value})} /><Field label="Email address" type="email" required value={form.email} onChange={e => setForm({...form, email: e.target.value})} /><Field label="Phone number" required value={form.phone} onChange={e => setForm({...form, phone: e.target.value})} /></div><Field as="textarea" label="Address" required value={form.address} onChange={e => setForm({...form, address: e.target.value})} /><Button>Update Profile</Button></Card></form></div>;
}

export function ChangePassword() {
  const {session, notify} = useApp(); const [form, setForm] = useState({oldPassword: '', newPassword: '', confirmPassword: ''});
  const submit = async e => {e.preventDefault(); if (form.newPassword !== form.confirmPassword) return notify('New passwords do not match.', 'error'); try {await apiRequest(`${endpoints.changePassword}${session.user.userId || session.user._id}`, {method: 'PUT', token: session.token, body: JSON.stringify(form)}); setForm({oldPassword: '', newPassword: '', confirmPassword: ''}); notify('Password changed successfully.');} catch (error) {notify(error.message, 'error');}};
  return <div className="page"><PageHeader eyebrow="Account security" title="Change Password" text="Choose a strong password that you do not use elsewhere." /><Card className="narrow-form"><LockKeyhole size={34} /><form onSubmit={submit}><Field label="Current password" type="password" required value={form.oldPassword} onChange={e => setForm({...form, oldPassword: e.target.value})} /><Field label="New password" type="password" required value={form.newPassword} onChange={e => setForm({...form, newPassword: e.target.value})} /><Field label="Confirm new password" type="password" required value={form.confirmPassword} onChange={e => setForm({...form, confirmPassword: e.target.value})} /><Button>Update Password</Button></form></Card></div>;
}

export function Privacy() {
  return <div className="page"><PageHeader eyebrow="Trust and transparency" title="Privacy Policy" text="A clear overview of how account and booking data is used in Merrage." /><div className="policy"><Card><h2>Information we use</h2><p>Profile details, contact information, service listings, booking dates, and messages are used to operate the wedding services marketplace.</p></Card><Card><h2>Bookings and vendors</h2><p>Relevant booking information is shared with the selected vendor and platform administrators to coordinate your request.</p></Card><Card><h2>Account security</h2><p>Keep your password private and contact support if you notice unexpected activity on your account.</p></Card><Card><h2>Your choices</h2><p>You can update profile details from the account page and contact support for questions about your information.</p></Card></div></div>;
}
