/* eslint-disable no-unused-vars */
import {Camera, LockKeyhole, Mail, MapPin, Phone, ShieldCheck, UserRound} from 'lucide-react';
import {useState} from 'react';
import {Button, Card, Field, PageHeader} from '../../components/UI';
import {useApp} from '../../lib/AppContext';
import {apiRequest, endpoints, unwrap} from '../../lib/api';

export default function EditProfile({vendor = false}) {
  const {session, updateSessionUser, notify} = useApp(); const user = session.user; const [form, setForm] = useState({name: user.name || '', email: user.email || '', phone: user.phone || '', address: user.address || ''}); const [photo, setPhoto] = useState(null);
  const submit = async e => {e.preventDefault(); const body = new FormData(); Object.entries(form).forEach(([k, v]) => body.append(k, v)); if (photo) body.append('profileImage', photo); try {const response = await apiRequest(endpoints.editProfile, {method: 'PUT', token: session.token, body}); updateSessionUser({...form, ...(photo ? {profileImage: URL.createObjectURL(photo)} : {}), ...unwrap(response)}); notify('Profile updated successfully.');} catch (error) {notify(error.message, 'error');}};
  return <div className="page"><PageHeader eyebrow={vendor ? 'Vendor profile' : 'Personal profile'} title="Edit Profile" text="These details are sent to the profile update API and shown across your account." /><form className="edit-profile-layout" onSubmit={submit}><Card className="photo-upload-card"><div className="profile-photo"><img src={photo ? URL.createObjectURL(photo) : user.profileImage || '/assets/image/zz.jpg'} alt="" /><label><Camera /><input type="file" accept="image/*" onChange={e => setPhoto(e.target.files[0])} /></label></div><h3>{vendor ? 'Business photo' : 'Profile photo'}</h3><p>{photo ? `${photo.name} is ready to upload.` : 'Choose a clear photo to update your account.'}</p></Card><Card className="form-card"><span className="eyebrow">Editable details</span><h2>{vendor ? 'Business details' : 'Personal details'}</h2><div className="form-grid"><Field label={vendor ? 'Business or contact name' : 'Full name'} required value={form.name} onChange={e => setForm({...form, name: e.target.value})} /><Field label="Email address" type="email" required value={form.email} onChange={e => setForm({...form, email: e.target.value})} /><Field label="Phone number" required value={form.phone} onChange={e => setForm({...form, phone: e.target.value})} /></div><Field as="textarea" label="Address" required value={form.address} onChange={e => setForm({...form, address: e.target.value})} /><Button>Update Profile</Button></Card></form></div>;
}
